In [1]:
import numpy as np

# Q1

In [7]:
# 1-4-a
x = np.matrix('0 3 1; 1 3 1; 0 1 1; 1 1 1')
w_0 = np.matrix('-2;1; 0')
s_0 = 1/(1+np.exp(-x*w_0))
s_0

matrix([[ 0.95257413],
        [ 0.73105858],
        [ 0.73105858],
        [ 0.26894142]])

In [8]:
# 1-4-b
y = np.matrix('1;1;0;0')
lam = 0.07
DJ = 2*lam*w_0 - x.T*(y - s_0)
lamM = np.diag(np.array([lam, lam, 0]))
HJ = 2*lamM + x.T * np.diag(np.array(s_0).reshape(1,4)[0]) * x
w_1 = w_0 - np.linalg.inv(HJ)*DJ
w_1

matrix([[-1.4288194 ],
        [ 1.46502203],
        [-1.51608461]])

In [9]:
# 1-4-c
s_1 = 1/(1+np.exp(-x*w_1))
s_1

matrix([[ 0.94679758],
        [ 0.81002338],
        [ 0.48723713],
        [ 0.18544525]])

In [10]:
# 1-4-d
DJ = 2*lam*w_1 - x.T*(y - s_1)
HJ = 2*lamM + x.T * np.diag(np.array(s_1).reshape(1,4)[0]) * x
w_2 = w_1 - np.linalg.inv(HJ)*DJ
w_2

matrix([[-1.06301781],
        [ 1.6171155 ],
        [-2.12744786]])